export default {
content: [
"./index.html",
"./src/**/*.{js,ts,jsx,tsx}",
],
theme: {
extend: {
colors: {
"secondary-fixed-dim": "#c8c6c2",
"surface-bright": "#fff8f4",
"surface-container": "#f5ece5",
"background": "#fff8f4",
"tertiary-fixed": "#ffdcc4",
"on-background": "#1f1b17",
"surface-container-lowest": "#ffffff",
"surface": "#fff8f4",
"surface-container-high": "#f0e7df",
"surface-container-highest": "#eae1da",
"on-tertiary-fixed": "#2f1400",
"on-tertiary-fixed-variant": "#6f3800",
"on-secondary-fixed-variant": "#474744",
"on-primary-fixed-variant": "#474746",
"on-tertiary-container": "#bb7336",
"on-surface-variant": "#444748",
"primary-container": "#1c1b1b",
"on-primary": "#ffffff",
"surface-dim": "#e1d8d2",
"secondary-fixed": "#e4e2dd",
"primary-fixed": "#e5e2e1",
"surface-tint": "#5f5e5e",
"surface-variant": "#eae1da",
"surface-container-low": "#fbf2eb",
"tertiary-fixed-dim": "#ffb780",
"on-secondary-fixed": "#1b1c19",
"inverse-surface": "#34302b",
"tertiary": "#000000",
"secondary": "#5e5e5b",
"on-error": "#ffffff",
"primary-fixed-dim": "#c8c6c5",
"on-secondary": "#ffffff",
"on-tertiary": "#ffffff",
"on-primary-fixed": "#1c1b1b",
"outline-variant": "#c4c7c7",
"outline": "#747878",
"on-secondary-container": "#63635f",
"on-surface": "#1f1b17",
"inverse-on-surface": "#f8efe8",
"error-container": "#ffdad6",
"on-error-container": "#93000a",
"on-primary-container": "#858383",
"inverse-primary": "#c8c6c5",
"tertiary-container": "#2f1400",
"secondary-container": "#e1dfdb",
"primary": "#000000",
"error": "#ba1a1a"
},
fontFamily: {
"serif": ["Noto Serif"],
"sans": ["Be Vietnam Pro"]
}
},
},
plugins: [],
}

